server:
  port: 3010

app:
  bondMoviesApiUrl: ${BOND_MOVIES_API_URL:http://bond-movies-api-nodejs:3001}
  movieMetadataApiUrl: ${MOVIE_METADATA_API_URL:http://movie-metadata-api-nodejs:3004}

kafka:
  topic: BondMoviesToBeProcessed
  brokers: kafka1:19092
  groupId: BondProcessingConsumerGroup
  partitionAssignor: org.apache.kafka.clients.consumer.RangeAssignor
